### ISSUE TITLE
Object reference error

### ISSUE THREAD

**Issue by bottasbacsi** [tmk907/TikTokDownloader#2]
I was using this great program for weeks but its stopped working now. I'm getting this error with HAR:
![TikTokDownloader_iUlVw320oI](https://user-images.githubusercontent.com/36135372/105596416-fbbd6080-5d93-11eb-8cf3-e1ebd5075f6b.png)

Can you take a look at it please?
Thank you!

**Comment by tmk907** [comment]
Fixed
[https://github.com/tmk907/TikTokDownloader/releases/tag/1.4](https://github.com/tmk907/TikTokDownloader/releases/tag/1.4)
