### ISSUE TITLE
Download from har showing blank screen

### ISSUE THREAD

**Issue by ravinot** [tmk907/TikTokDownloader#4]
Hello,

I've tried using this program but I'm not having any luck using an har file that I downloaded via Firefox.

I've followed the steps from here https://github.com/tmk907/TikTokDownloader, installed .Net Core 3.1 and made my TikTok liked list public.

The program runs, I choose a download folder, then when I click the button "Download from har" it states "Downloading" in the MainWindow screen and asks me to choose a file. I choose my har and it takes me back to the main window, but nothing seems to happen and there is no indication the program is downloading anything.

Could you please confirm if I am following the right steps?

Thanks

**Comment by tmk907** [comment]
TikTok changed response format and app couldn't find download links.
I updated application, you can download new version [here](https://github.com/tmk907/TikTokDownloader/releases/tag/1.5)
