### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: JSON integer 5300000000 is too large or small for an Int32. Path 'itemList[0].authorStats.heart', line 1, position 4264.

### ISSUE THREAD

**Issue by BluestCloud** [tmk907/TikTokDownloader#5]
Getting a bunch of these errors, see log file.  'heart' appears be the type long, wonder why it's saying Int32.
[logs.txt](https://github.com/tmk907/TikTokDownloader/files/6887359/logs.txt)
 Also can we show the counts of the number of videos in the HAR file, looks like many aren't getting downloaded.

**Comment by tmk907** [comment]
[Fixed](https://github.com/tmk907/TikTokDownloader/releases)
Number of videos in har file is shown in progress text
