### ISSUE TITLE
sorry not an issue but i dont know how to contact you on this website

### ISSUE THREAD

**Issue by JONJONNO** [tmk907/TikTokDownloader#6]
i am trying to download all my liked tiktoks however when i scrolled all the way down on my likes i am unable to get a har file with any data on it. 
i have a lot of tiktoks im trying to download but chrome wont give me a har file for more than 60 videos.
please contact me :C

**Comment by tmk907** [comment]
I just tried to download har using Chrome, but Chrome did not load any videos. However, Edge and Opera work fine. I don't know if you have a similar problem, but can you try downloading har using Edge or Opera?

**Comment by JONJONNO** [comment]
Yeh I can it's not a problem I can try edge but since I'm trying to download my whole like history it may be an issue with the max file size of a har from the browser.Do you know anyway I can download my videos easie cuz I'm scrallikg for a while to have to get any...On 4 Sep 2021 19:09, Tomasz Walecki ***@***.***> wrote:
I just tried to download har using Chrome, but Chrome did not load any videos. However, Edge and Opera work fine. I don't know if you have a similar problem, but can you try downloading har using Edge or Opera?

**Comment by tmk907** [comment]
I'm working on improved application where its not required to manually download har file. Its easier to use but there are few more steps to install it.

Install [certificate](https://1drv.ms/u/s!AkXYBLnVAzYNrF4E37kpiFVR5_X7?e=F5cqvQ)
- double click .cer file
- install certificate
- local computer
- select certificate storage: "trusted people"

Install msix file [MyTiktokBackup](https://install.appcenter.ms/users/tomek_w-l5a7/apps/mytiktokbackup/distribution_groups/public%20beta)

Open app, go to settings, choose download folder
Now you can search for user in browser. While you scroll through videos, favorites videos count will update.
You dont have to download all videos at once, but next time you open app you have to scroll through videos again.

**Comment by headassic** [comment]
fuck i been stressing over the same issue, only opera works with large file sets. it does some temporary file in the same directory to fit it all in. opera took 2000 videos.

**Comment by tmk907** [comment]
I created new app for downloading tiktok videos.  You can download it from [Microsoft Store](https://www.microsoft.com/store/apps/9NPJL9MCPRKD?ocid=github)

**Comment by headassic** [comment]
I tried that but it appears I broke my store in trying to block microsoft telemetry. And I cannot build it properly from the source code because the windows sdk will not install properly either, something about start menu folder ownership privlages smh. I Tried making trustedinstaller the owner and it still didn’t work.

**Comment by tmk907** [comment]
Try to install this package [https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.9](https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.9)

**Comment by headassic** [comment]
Thanks for trying to help I really appreciate it, I am getting this error code with the msi installer
App Installer failed to install package dependencies. Ask the developer for  package.

________________________________

**Comment by tmk907** [comment]
It's first time I release this kind of application and did't include neccessary dependencies.
I updated release and added `Dependencies.7z`. Please unpack it and install 3 libraries. I hope this time it will work fine.
