### ISSUE TITLE
Downloading all favorited videos 

### ISSUE THREAD

**Issue by sabaak95** [tmk907/TikTokDownloader#9]
Hi,
I actually looked up online a lot about this but could not find a repo talking about how we can download only the favorite videos, all at once. Is there any way in that regard?

**Comment by tmk907** [comment]
I created new app MyTikTokBackup. You can download all your favorite videos, hovewer it's not fully automatically, you need to scroll your favorite videos page first. You can download it from [Microsoft Store](https://www.microsoft.com/store/apps/9NPJL9MCPRKD?ocid=github)

**Comment by sabaak95** [comment]
I think this downloads all my "liked" videos. I want the one which is only appearing in the mobile version of the app and where you can add the video to favorites, and then download them all

**Comment by tmk907** [comment]
I get it now. 
Favorite videos are listed in file 'user_data.json'. You can get this file if you request your data in mobile app (Privacy> Personalize and data > Download TikTok Data). I will add feature to MyTikTokBackup to parse this file and download favorite videos.
https://github.com/tmk907/MyTikTokBackup/issues/1

**Comment by tmk907** [comment]
New version is in store

**Comment by sabaak95** [comment]
Thanks!
I just have one question. I need to import user data whenever it gets ready
right? and then the download will begin?
Can you explain a little bit about the instructions?
btw I had my data but it was in text format, so I needed to request for json

**Comment by tmk907** [comment]
First, click the 'Import User Data' button and select the json file. After the app finds the links to download the video, click the 'Download' button.

**Comment by sabaak95** [comment]
although i added it, it does not find all of them, 
(my total is 370, once it finds 29, once 38, it just changes) .
what is worse is that the download button does nothing, even for this 29 or whatsoever 38 ones. (error in download tab)

**Comment by tmk907** [comment]
I will move this to MyTIkTokBackup issues  https://github.com/tmk907/MyTikTokBackup/issues/1
